"""removed direct relation between Center and Appointments

Revision ID: 1045ce3d662b
Revises: d628d571c245
Create Date: 2024-06-09 19:20:35.453697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1045ce3d662b'
down_revision: Union[str, None] = 'd628d571c245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_ibfk_1', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'center_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('center_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('appointments_ibfk_1', 'appointments', 'centers', ['center_id'], ['id'])
    # ### end Alembic commands ###
