"""first revision


Revision ID: 17f01e46f964
Revises: 
Create Date: 2024-05-31 14:30:58.347857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f01e46f964'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('center', sa.Text(), nullable=False),
    sa.Column('year', sa.Text(), nullable=False),
    sa.Column('month', sa.Text(), nullable=False),
    sa.Column('month_day', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.Text(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
