"""added leader to month again

Revision ID: 18645ad40805
Revises: 3a3f649b35bd
Create Date: 2024-06-17 23:30:31.284819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18645ad40805'
down_revision: Union[str, None] = '3a3f649b35bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('months', sa.Column('leader', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('months', 'leader')
    # ### end Alembic commands ###
