"""added month_id to appointments

Revision ID: 1b919afab466
Revises: 05a012c137be
Create Date: 2024-06-02 00:16:03.031838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b919afab466'
down_revision: Union[str, None] = '05a012c137be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('month_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'months', ['month_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'month_id')
    # ### end Alembic commands ###
