"""added center_id to Month and relationship month-center and added is_populated to month

Revision ID: 1fa603c0b674
Revises: 47bdf1a529da
Create Date: 2024-06-09 12:50:41.902455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa603c0b674'
down_revision: Union[str, None] = '47bdf1a529da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('months', sa.Column('center_id', sa.Integer(), nullable=False))
    op.add_column('months', sa.Column('is_populated', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'months', 'centers', ['center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'months', type_='foreignkey')
    op.drop_column('months', 'is_populated')
    op.drop_column('months', 'center_id')
    # ### end Alembic commands ###
