"""changed is_locked to is_visible

Revision ID: 28af0483ed71
Revises: 9fbede1f86b5
Create Date: 2024-07-13 16:57:49.267147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '28af0483ed71'
down_revision: Union[str, None] = '9fbede1f86b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_visible')
    # ### end Alembic commands ###
