"""added is_sudo to User

Revision ID: 2a2761fe1054
Revises: 95317ffc56b9
Create Date: 2024-06-12 12:40:46.182909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2761fe1054'
down_revision: Union[str, None] = '95317ffc56b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_sudo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_sudo')
    # ### end Alembic commands ###
