"""corrected message's properties

Revision ID: 39578f3691ac
Revises: 7a7a0cc80f39
Create Date: 2024-07-14 01:00:43.954471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39578f3691ac'
down_revision: Union[str, None] = '7a7a0cc80f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
