"""added is_root to User

Revision ID: 3f6c06736d0d
Revises: 2a2761fe1054
Create Date: 2024-06-12 12:44:20.008948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6c06736d0d'
down_revision: Union[str, None] = '2a2761fe1054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_root', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_root')
    # ### end Alembic commands ###
