"""changed Request.receivers to Request.receivers_code

Revision ID: 46905bb5d9cf
Revises: eb4db470f967
Create Date: 2024-06-16 18:40:20.363648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46905bb5d9cf'
down_revision: Union[str, None] = 'eb4db470f967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
