"""recreated relation between Appointment and Request and added is_confirmed to Appointment

Revision ID: 46cdd5550eeb
Revises: 80a40da9f1e8
Create Date: 2024-06-23 22:16:15.708809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46cdd5550eeb'
down_revision: Union[str, None] = '80a40da9f1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('request_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'requests', ['request_id'], ['id'])
    op.add_column('requests', sa.Column('response', sa.Text(), nullable=True))
    op.drop_column('requests', 'authorized')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('authorized', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('requests', 'response')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'is_confirmed')
    op.drop_column('appointments', 'request_id')
    # ### end Alembic commands ###
