"""removed next/previous from Month

Revision ID: 47bdf1a529da
Revises: 52c72295a6af
Create Date: 2024-06-09 12:23:22.971281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47bdf1a529da'
down_revision: Union[str, None] = '52c72295a6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('months_ibfk_1', 'months', type_='foreignkey')
    op.drop_constraint('months_ibfk_2', 'months', type_='foreignkey')
    op.drop_column('months', 'next_month_id')
    op.drop_column('months', 'previous_month_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('months', sa.Column('previous_month_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('months', sa.Column('next_month_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('months_ibfk_2', 'months', 'months', ['previous_month_id'], ['id'])
    op.create_foreign_key('months_ibfk_1', 'months', 'months', ['next_month_id'], ['id'])
    # ### end Alembic commands ###
