"""changed receivers for requestees in request - undo again

Revision ID: 5041654b5a04
Revises: 4df40e9d2472
Create Date: 2024-08-11 22:00:19.401642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5041654b5a04'
down_revision: Union[str, None] = '4df40e9d2472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
