"""added assosciation table and associated Month and days many to many

Revision ID: 733f4fdc6ed7
Revises: f14996659c2a
Create Date: 2024-06-09 15:38:45.218630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '733f4fdc6ed7'
down_revision: Union[str, None] = 'f14996659c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month_day',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ),
    sa.PrimaryKeyConstraint('day_id', 'month_id')
    )
    op.drop_constraint('days_ibfk_1', 'days', type_='foreignkey')
    op.drop_column('days', 'month_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('month_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('days_ibfk_1', 'days', 'months', ['month_id'], ['id'])
    op.drop_table('month_day')
    # ### end Alembic commands ###
