"""simplified Appointment and added Month

Revision ID: 78f7eb8d5936
Revises: 17f01e46f964
Create Date: 2024-06-01 23:40:41.891892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78f7eb8d5936'
down_revision: Union[str, None] = '17f01e46f964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('appointments', 'month_day')
    op.drop_column('appointments', 'week_day')
    op.drop_column('appointments', 'month')
    op.drop_column('appointments', 'is_holiday')
    op.drop_column('appointments', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('year', mysql.TEXT(), nullable=False))
    op.add_column('appointments', sa.Column('is_holiday', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('month', mysql.TEXT(), nullable=False))
    op.add_column('appointments', sa.Column('week_day', mysql.TEXT(), nullable=False))
    op.add_column('appointments', sa.Column('month_day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'date')
    # ### end Alembic commands ###
