"""removed relation between center and month and made the relation between month and days one to many

Revision ID: 8631497cabb8
Revises: 1045ce3d662b
Create Date: 2024-06-10 19:05:43.393527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8631497cabb8'
down_revision: Union[str, None] = '1045ce3d662b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('month_day_association')
    # op.add_column('appointments', sa.Column('center_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'appointments', 'centers', ['center_id'], ['id'])
    # op.add_column('days', sa.Column('month_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'days', 'months', ['month_id'], ['id'])
    
    op.drop_constraint('months_ibfk_1', 'months', type_='foreignkey')

    op.drop_index('uq_center_month_year', table_name='months')
    
    op.create_unique_constraint('uq_month_year', 'months', ['number', 'year'])
    
    op.drop_column('months', 'center_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('months', sa.Column('center_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('months_ibfk_1', 'months', 'centers', ['center_id'], ['id'])
    op.drop_constraint('uq_month_year', 'months', type_='unique')
    op.create_index('uq_center_month_year', 'months', ['center_id', 'number', 'year'], unique=True)
    op.drop_constraint(None, 'days', type_='foreignkey')
    op.drop_column('days', 'month_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'center_id')
    op.create_table('month_day',
    sa.Column('day_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('month_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], name='month_day_ibfk_1'),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], name='month_day_ibfk_2'),
    sa.PrimaryKeyConstraint('day_id', 'month_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
