"""created a request_appointment_association -- fixed misspelling -- saved this time

Revision ID: 8b39bbae90e2
Revises: a01328afaa50
Create Date: 2024-07-08 21:02:51.110841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b39bbae90e2'
down_revision: Union[str, None] = 'a01328afaa50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
