"""changed is_locked to is_visible

Revision ID: 9fbede1f86b5
Revises: 9cddae48a11c
Create Date: 2024-07-13 16:57:16.129102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbede1f86b5'
down_revision: Union[str, None] = '9cddae48a11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
