"""created a request_appointment_association -- fixed misspelling

Revision ID: a01328afaa50
Revises: 5cd1d6f9216b
Create Date: 2024-07-08 21:01:58.507033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01328afaa50'
down_revision: Union[str, None] = '5cd1d6f9216b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
