"""added Request.authorized

Revision ID: afe7d5bdafe1
Revises: 0323603121f4
Create Date: 2024-06-16 20:49:46.039335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe7d5bdafe1'
down_revision: Union[str, None] = '0323603121f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'authorized')
    # ### end Alembic commands ###
