"""deleted apparently unecessarymonth/day association

Revision ID: b4abacb2efef
Revises: fc4dc9fc3ba5
Create Date: 2024-07-08 20:30:44.555049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4abacb2efef'
down_revision: Union[str, None] = 'fc4dc9fc3ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
