"""added an info column to request

Revision ID: b56faaba957f
Revises: c8e1ae87bd45
Create Date: 2024-07-17 22:59:18.047533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56faaba957f'
down_revision: Union[str, None] = 'c8e1ae87bd45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'info')
    # ### end Alembic commands ###
