"""added pre_approved_vacation to user

Revision ID: c5190baa39f4
Revises: e2921f31c5da
Create Date: 2024-09-14 23:24:49.845984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5190baa39f4'
down_revision: Union[str, None] = 'e2921f31c5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pre_approved_vacation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pre_approved_vacation')
    # ### end Alembic commands ###
