"""added uniqueConstraint(center, month, year) to Month

Revision ID: cd47aa810346
Revises: 1fa603c0b674
Create Date: 2024-06-09 12:54:02.909552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd47aa810346'
down_revision: Union[str, None] = '1fa603c0b674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_center_month_year', 'months', ['center_id', 'number', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_center_month_year', 'months', type_='unique')
    # ### end Alembic commands ###
