"""changed receivers for requestees in request

Revision ID: dd6d37dedd06
Revises: e2921f31c5da
Create Date: 2024-08-11 21:40:09.341171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd6d37dedd06'
down_revision: Union[str, None] = 'e2921f31c5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('requestee_code', sa.Text(), nullable=False))
    op.drop_column('requests', 'receivers_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('receivers_code', mysql.TEXT(), nullable=False))
    op.drop_column('requests', 'requestee_code')
    # ### end Alembic commands ###
