"""added unique constraint to appointment to avoid repeated appointments (same day, doctor and hour, but not same center)

Revision ID: eb4db470f967
Revises: 3f6c06736d0d
Create Date: 2024-06-16 17:42:40.175076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4db470f967'
down_revision: Union[str, None] = '3f6c06736d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_appointment', 'appointments', ['user_id', 'day_id', 'hour'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_appointment', 'appointments', type_='unique')
    # ### end Alembic commands ###
