"""added is_locked and is_current to month

Revision ID: ebf4b6b4e58e
Revises: 1b919afab466
Create Date: 2024-06-02 16:02:34.939099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf4b6b4e58e'
down_revision: Union[str, None] = '1b919afab466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('months', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('months', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('months', 'is_locked')
    op.drop_column('months', 'is_current')
    # ### end Alembic commands ###
