"""changed weekindex from text to int

Revision ID: fc23456d4c14
Revises: bcf373571370
Create Date: 2024-06-04 23:37:38.836779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc23456d4c14'
down_revision: Union[str, None] = 'bcf373571370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_appointments', 'week_day',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_appointments', 'week_day',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
